{% set name = "moar" %}
{% set version = "1.28.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/walles/moar/archive/v{{ version }}.tar.gz
  sha256: 4b36c8e74d06c360f241af3de90bbe43ab6e6585b7cddfe8723e3c6723907a56

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - moar --help

about:
  home: https://github.com/walles/moar
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  dev_url: https://github.com/walles/moar

extra:
  recipe-maintainers:
    - danielnachun
