{% set name = "moar" %}
{% set version = "1.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/walles/moar/archive/v{{ version }}.tar.gz
  sha256: 72a9d62d62c84fb3a07f65fae27cdf9065d988d5f7d174f56f6eed7c74ec2247

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - moar --help

about:
  home: https://github.com/walles/moar
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  dev_url: https://github.com/walles/moar

extra:
  recipe-maintainers:
    - danielnachun
