{% set name = "moar" %}
{% set version = "1.32.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/walles/moar/archive/v{{ version }}.tar.gz
  sha256: 5bb5906ae3d6e03e092ed63e862385e77d35875fc2cae761eee835c754814400

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - moar --help

about:
  home: https://github.com/walles/moar
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Nice to use pager for humans
  dev_url: https://github.com/walles/moar

extra:
  recipe-maintainers:
    - danielnachun
